// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecrabttgqnzepxqvpnsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjcmFidHRncW56ZXB4cXZwbnNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDAyNTYsImV4cCI6MjA2OTg3NjI1Nn0.z5gRat6GJ9PEUueEXYlRpPEAxhK-e31PQdwDmZ5spuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});